# Generated by Django 3.0.8 on 2020-07-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='title',
            field=models.CharField(default='Answer', max_length=255),
        ),
    ]
